name: URLReader
options:
  bundleIdPrefix: com.kareemf
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    DEVELOPMENT_TEAM: 8C7EB23ZZP
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  URLReader:
    type: application
    platform: iOS
    sources:
      - path: URLReader
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kareemf.URLReader
        INFOPLIST_FILE: URLReader/Info.plist
        CODE_SIGN_ENTITLEMENTS: URLReader/URLReader.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_CFBundleDisplayName: "URL Reader"
        INFOPLIST_KEY_CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        INFOPLIST_KEY_CFBundleName: "$(PRODUCT_NAME)"
        INFOPLIST_KEY_CFBundleShortVersionString: "$(MARKETING_VERSION)"
        INFOPLIST_KEY_CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        INFOPLIST_KEY_CFBundleExecutable: "$(EXECUTABLE_NAME)"
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
    dependencies:
      - target: URLReaderShare
        embed: true
        codeSign: true
    entitlements:
      path: URLReader/URLReader.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.kareemf.URLReader

  URLReaderShare:
    type: app-extension
    platform: iOS
    sources:
      - path: ShareExtension
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kareemf.URLReader.ShareExtension
        PRODUCT_NAME: URLReaderShare
        INFOPLIST_FILE: ShareExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: ShareExtension/ShareExtension.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
        SKIP_INSTALL: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Read Aloud"
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
          - "@executable_path/../../Frameworks"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
    entitlements:
      path: ShareExtension/ShareExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.kareemf.URLReader

schemes:
  URLReader:
    build:
      targets:
        URLReader: all
        URLReaderShare: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  URLReaderShare:
    build:
      targets:
        URLReaderShare: all
    run:
      config: Debug
      askForAppToLaunch: true
